version: "3.0"

services:
  nginx:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./wlasny.key:/etc/ssl/private/wlasny.key
      - ./wlasny.crt:/etc/ssl/certs/wlasny.crt
    depends_on:
      -  web
  web:
    build: .
    command: gunicorn app:app --bind 0.0.0.0:8000
    expose:
      -  8000
